using System.Collections.Generic;
using RandomDungeonWithBluePrint;
using UnityEditor;
using UnityEngine;

namespace Editor
{
    public partial class FieldBluePrintEditor
    {
        private void GenerateFieldBluePrint()
        {
            // 不正なマップのチェック
            if (!IsValidMap())
            {
                EditorUtility.DisplayDialog("Invalid Map", "Cannot generate FieldBluePrint: Invalid map configuration.", "OK");
                return;
            }

            // エリアのサイズを取得
            Vector2Int boardSize = new Vector2Int(areaSize.x, areaSize.y);

            List<FieldBluePrint.Section> blueprintSections = new List<FieldBluePrint.Section>();
            for (int i = 0; i < this.sections.Count; i++)
            {
                var section = this.sections[i];

                // RoomGenerationTypeをFieldBluePrintの形式に変換
                bool roomIndispensable = section.roomGenerationType == RoomGenerationType.Always;
                int makeRoomWeight = section.roomGenerationType == RoomGenerationType.Never ? 0 : 1;

                // Y座標を反転（エディターの座標系からFieldBluePrintの座標系に変換）
                RectInt flippedRect = new RectInt(
                    section.rect.x,
                    section.rect.y,
                    section.rect.width,
                    section.rect.height
                );

                var blueprintSection = new FieldBluePrint.Section(
                    i,
                    roomIndispensable,
                    makeRoomWeight,
                    flippedRect,
                    section.minRoomSize
                );
                blueprintSections.Add(blueprintSection);
            }

            // ConnectionをFieldBluePrint.Connectionに変換
            List<FieldBluePrint.Connection> blueprintConnections = new List<FieldBluePrint.Connection>();
            foreach (var connection in connections)
            {
                if (connection.fromSection != null && connection.toSection != null)
                {
                    int fromIndex = this.sections.IndexOf(connection.fromSection);
                    int toIndex = this.sections.IndexOf(connection.toSection);

                    if (fromIndex >= 0 && toIndex >= 0)
                    {
                        blueprintConnections.Add(new FieldBluePrint.Connection(fromIndex, toIndex));
                    }
                }
            }

            // FieldBluePrintを作成
            var blueprint = new FieldBluePrint(
                boardSize,
                minRoomNum,
                maxRoomNum,
                minRandomBranchNum,
                maxRandomBranchNum,
                autoGenerateDefaultConnections,
                blueprintSections,
                blueprintConnections
            );

            // アセットとして保存
            string path = AssetDatabase.GetAssetPath(Selection.activeObject);
            if (string.IsNullOrEmpty(path))
            {
                path = "Assets";
            }
            else if (!System.IO.Directory.Exists(path))
            {
                path = System.IO.Path.GetDirectoryName(path);
            }

            string assetPathAndName = AssetDatabase.GenerateUniqueAssetPath(path + $"/{blueprintName}.asset");
            AssetDatabase.CreateAsset(blueprint, assetPathAndName);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            EditorUtility.FocusProjectWindow();
            Selection.activeObject = blueprint;

        }

        private void SaveBlueprint()
        {
            if (currentBlueprint == null)
            {
                EditorUtility.DisplayDialog("Error", "No blueprint loaded to save.", "OK");
                return;
            }

            // 不正なマップのチェック
            if (!IsValidMap())
            {
                EditorUtility.DisplayDialog("Invalid Map", "Cannot save FieldBluePrint: Invalid map configuration.", "OK");
                return;
            }

            // 既存のBlueprintを更新
            Undo.RecordObject(currentBlueprint, "Save FieldBluePrint");

            // 名前を更新
            if (!string.IsNullOrEmpty(blueprintName))
            {
                currentBlueprint.name = blueprintName;

                // アセットファイル名も更新
                string currentPath = AssetDatabase.GetAssetPath(currentBlueprint);
                if (!string.IsNullOrEmpty(currentPath))
                {
                    string directory = System.IO.Path.GetDirectoryName(currentPath);
                    string newPath = System.IO.Path.Combine(directory, blueprintName + ".asset");

                    // ファイル名が変更された場合のみリネーム
                    if (currentPath != newPath)
                    {
                        AssetDatabase.RenameAsset(currentPath, blueprintName);
                    }
                }
            }

            // エリアのサイズを更新
            currentBlueprint.GetType().GetField("size", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)
                ?.SetValue(currentBlueprint, new Vector2Int(areaSize.x, areaSize.y));

            // パラメータを更新
            currentBlueprint.GetType().GetField("minRoomNum", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)
                ?.SetValue(currentBlueprint, minRoomNum);
            currentBlueprint.GetType().GetField("maxRoomNum", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)
                ?.SetValue(currentBlueprint, maxRoomNum);
            currentBlueprint.GetType().GetField("minRandomBranchNum", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)
                ?.SetValue(currentBlueprint, minRandomBranchNum);
            currentBlueprint.GetType().GetField("maxRandomBranchNum", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)
                ?.SetValue(currentBlueprint, maxRandomBranchNum);
            currentBlueprint.GetType().GetField("autoGenerateDefaultConnections", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)
                ?.SetValue(currentBlueprint, autoGenerateDefaultConnections);

            // セクションを更新
            var sectionsField = currentBlueprint.GetType().GetField("sections", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
            var sectionsList = sectionsField?.GetValue(currentBlueprint) as System.Collections.Generic.List<FieldBluePrint.Section>;
            if (sectionsList != null)
            {
                sectionsList.Clear();
                for (int i = 0; i < this.sections.Count; i++)
                {
                    var section = this.sections[i];
                    bool roomIndispensable = section.roomGenerationType == RoomGenerationType.Always;
                    int makeRoomWeight = section.roomGenerationType == RoomGenerationType.Never ? 0 : 1;

                    // Y座標を反転（エディターの座標系からFieldBluePrintの座標系に変換）
                    RectInt flippedRect = new RectInt(
                        section.rect.x,
                        areaSize.y - section.rect.y - section.rect.height,
                        section.rect.width,
                        section.rect.height
                    );

                    var blueprintSection = new FieldBluePrint.Section(
                        i,
                        roomIndispensable,
                        makeRoomWeight,
                        flippedRect,
                        section.minRoomSize
                    );
                    sectionsList.Add(blueprintSection);
                }
            }

            // コネクションを更新
            var connectionsField = currentBlueprint.GetType().GetField("connections", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
            var connectionsList = connectionsField?.GetValue(currentBlueprint) as System.Collections.Generic.List<FieldBluePrint.Connection>;
            if (connectionsList != null)
            {
                connectionsList.Clear();
                foreach (var connection in connections)
                {
                    if (connection.fromSection != null && connection.toSection != null)
                    {
                        int fromIndex = this.sections.IndexOf(connection.fromSection);
                        int toIndex = this.sections.IndexOf(connection.toSection);

                        if (fromIndex >= 0 && toIndex >= 0)
                        {
                            connectionsList.Add(new FieldBluePrint.Connection(fromIndex, toIndex));
                        }
                    }
                }
            }

            // アセットを保存
            EditorUtility.SetDirty(currentBlueprint);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            EditorUtility.DisplayDialog("Success", "FieldBluePrint saved successfully!", "OK");
        }
    }
}
