using System.Collections.Generic;
using RandomDungeonWithBluePrint;
using UnityEditor;
using UnityEngine;

namespace Editor
{
    public partial class FieldBluePrintEditor : EditorWindow
    {
        [MenuItem("Assets/Open Field Blue Print Editor", false, 20)]
        public static void OpenFromProject() => OpenWindow();

        [MenuItem("Tools/Field Blue Print Editor")]
        public static void OpenWindow() => GetWindow<FieldBluePrintEditor>("Field Blue Print Editor");

        private List<SectionRect> sections = new List<SectionRect>();
        private List<Connection> connections = new List<Connection>();
        private SectionRect selectedSection = null;
        private Vector2 dragOffset;
        private bool resizing = false;
        private bool resizingArea = false;
        private bool creatingConnection = false;
        private SectionRect connectionStartSection;
        private SectionRect copiedSection = null;
        private Vector2Int resizeHandleType;
        private const int handleSize = 12;
        private const int gridSize = 1;
        private static readonly Vector2Int defaultMinRoomSize = new Vector2Int(6, 6);
        private static readonly Vector2Int defaultMinSectionSize = defaultMinRoomSize + new Vector2Int(4, 4);

        // FieldBluePrint生成パラメータ
        private string blueprintName = "";
        private int minRoomNum = 5;
        private int maxRoomNum = 10;
        private int minRandomBranchNum = 1;
        private int maxRandomBranchNum = 3;
        private bool autoGenerateDefaultConnections = true;

        // エリアサイズ（固定位置、サイズのみ変更可能）
        private Vector2Int areaSize = new Vector2Int(20, 20);

        // 編集対象のFieldBluePrintアセット
        private FieldBluePrint currentBlueprint = null;

        public enum RoomGenerationType
        {
            Always,     // 必ず作る
            Random,     // ランダムに作る
            Never       // 絶対に作らない
        }

        private class SectionRect
        {
            public RectInt rect;
            public RoomGenerationType roomGenerationType = RoomGenerationType.Random;
            public Vector2Int minRoomSize;
            public SectionRect(RectInt rect, RoomGenerationType roomGenerationType, Vector2Int minRoomSize)
            {
                this.rect = rect;
                this.roomGenerationType = roomGenerationType;
                this.minRoomSize = minRoomSize;
            }
            public SectionRect CopyWith(RectInt? rect=null, RoomGenerationType? roomGenerationType=null, Vector2Int? minRoomSize=null)
            {
                return new SectionRect(rect ?? this.rect, roomGenerationType ?? this.roomGenerationType, minRoomSize ?? this.minRoomSize);
            }
        }

        private class Connection
        {
            public SectionRect fromSection;
            public SectionRect toSection;
        }

        public void LoadBlueprint(FieldBluePrint blueprint)
        {
            currentBlueprint = blueprint;

            // 既存のデータをクリア

            sections.Clear();
            connections.Clear();
            selectedSection = null;

            // エリアサイズを設定

            areaSize = blueprint.Size;

            // 名前を設定
            blueprintName = blueprint.name;

            // パラメータを設定

            minRoomNum = blueprint.MinRoomNum;
            maxRoomNum = blueprint.MaxRoomNum;
            minRandomBranchNum = blueprint.MinRandomBranchNum;
            maxRandomBranchNum = blueprint.MaxRandomBranchNum;
            autoGenerateDefaultConnections = blueprint.AutoGenerateDefaultConnections;

            // セクションを読み込み（Y座標を反転）

            foreach (var section in blueprint.Sections)
            {
                // Y座標を反転（FieldBluePrintの座標系からエディターの座標系に変換）
                RectInt flippedRect = new RectInt(
                    section.Rect.x,
                    areaSize.y - section.Rect.y - section.Rect.height,
                    section.Rect.width,
                    section.Rect.height
                );

                var sectionRect = new SectionRect
                (
                    flippedRect,
                    RoomGenerationType.Random,
                    section.MinRoomSize
                );

                // RoomGenerationTypeを変換

                if (section.RoomIndispensable)
                {
                    sectionRect.roomGenerationType = RoomGenerationType.Always;
                }
                else if (section.MakeRoomWeight == 0)
                {
                    sectionRect.roomGenerationType = RoomGenerationType.Never;
                }
                else
                {
                    sectionRect.roomGenerationType = RoomGenerationType.Random;
                }


                sections.Add(sectionRect);
            }

            // コネクションを読み込み

            foreach (var connection in blueprint.Connections)
            {
                if (connection.From >= 0 && connection.From < sections.Count &&
                    connection.To >= 0 && connection.To < sections.Count)
                {
                    var newConnection = new Connection
                    {
                        fromSection = sections[connection.From],
                        toSection = sections[connection.To]
                    };
                    connections.Add(newConnection);
                }
            }


            Repaint();
        }

        private void LoadNewBlueprint()
        {
            string path = EditorUtility.OpenFilePanel("Load FieldBluePrint", "Assets", "asset");
            if (!string.IsNullOrEmpty(path))
            {
                // パスをAssets相対パスに変換
                if (path.StartsWith(Application.dataPath))
                {
                    path = "Assets" + path.Substring(Application.dataPath.Length);
                }

                var blueprint = AssetDatabase.LoadAssetAtPath<FieldBluePrint>(path);
                if (blueprint != null)
                {
                    LoadBlueprint(blueprint);
                }
                else
                {
                    EditorUtility.DisplayDialog("Error", "Selected file is not a valid FieldBluePrint asset.", "OK");
                }
            }
        }

        private void OnGUI()
        {
            // ウィンドウを分割
            Rect gridRect = new Rect(0, 0, position.width - 300, position.height);
            Rect propertyRect = new Rect(position.width - 300, 0, 300, position.height);

            // グリッドエリア
            GUI.BeginGroup(gridRect);
            DrawGridArea();
            GUI.EndGroup();

            // プロパティパネル
            GUI.BeginGroup(propertyRect);
            DrawPropertyPanel();
            GUI.EndGroup();

            HandleInput();

            // コネクション作成中は常に更新
            if (creatingConnection && connectionStartSection != null)
            {
                Repaint();
            }
        }

        private float drawScale = 20f; // 描画倍率
        private Vector2Int viewOffset = Vector2Int.zero; // 表示領域のオフセット

        private void DrawPropertyPanel()
        {
            GUILayout.BeginArea(new Rect(10, 10, 280, position.height - 20));

            GUILayout.Space(10);

            // タイトル
            GUILayout.Label("FieldBluePrint Editor", EditorStyles.boldLabel);

            GUILayout.Space(10);

            // 選択されたSectionの設定
            if (selectedSection != null)
            {
                GUILayout.Label("Selected Section Settings", EditorStyles.boldLabel);
                selectedSection.roomGenerationType = (RoomGenerationType)EditorGUILayout.EnumPopup("Room Generation", selectedSection.roomGenerationType);

                // Never以外の場合のみMin Room Sizeを表示
                if (selectedSection.roomGenerationType != RoomGenerationType.Never)
                {
                    EditorGUILayout.LabelField("Min Room Size");
                    EditorGUI.indentLevel++;

                    // X座標
                    int newMinRoomSizeX = EditorGUILayout.IntField("X", selectedSection.minRoomSize.x);
                    if (newMinRoomSizeX <= 0)
                    {
                        EditorGUILayout.HelpBox("X must be at least 1", MessageType.Warning);
                    }
                    else if (newMinRoomSizeX + 4 > selectedSection.rect.width)
                    {
                        EditorGUILayout.HelpBox($"X + 4 cannot exceed Section width (max: {selectedSection.rect.width - 4})", MessageType.Warning);
                    }
                    else
                    {
                        selectedSection.minRoomSize = new Vector2Int(newMinRoomSizeX, selectedSection.minRoomSize.y);
                    }

                    // Y座標
                    int newMinRoomSizeY = EditorGUILayout.IntField("Y", selectedSection.minRoomSize.y);
                    if (newMinRoomSizeY <= 0)
                    {
                        EditorGUILayout.HelpBox("Y must be at least 1", MessageType.Warning);
                    }
                    else if (newMinRoomSizeY + 4 > selectedSection.rect.height)
                    {
                        EditorGUILayout.HelpBox($"Y + 4 cannot exceed Section height (max: {selectedSection.rect.height - 4})", MessageType.Warning);
                    }
                    else
                    {
                        selectedSection.minRoomSize = new Vector2Int(selectedSection.minRoomSize.x, newMinRoomSizeY);
                    }

                    EditorGUI.indentLevel--;
                }
            }
            else
            {
                GUILayout.Label("No Section Selected", EditorStyles.boldLabel);
                EditorGUILayout.HelpBox("Select a section to edit its properties", MessageType.Info);
            }

            GUILayout.Space(10);

            // FieldBluePrint生成パラメータ
            GUILayout.Label("FieldBluePrint Settings", EditorStyles.boldLabel);

            blueprintName = EditorGUILayout.TextField("Blueprint Name", blueprintName);

            // Min Rooms (1以上、Section数以下)
            int newMinRoomNum = EditorGUILayout.IntField("Min Rooms", minRoomNum);
            if (newMinRoomNum < 1)
            {
                EditorGUILayout.HelpBox("Min Rooms must be at least 1", MessageType.Warning);
            }
            else if (newMinRoomNum > sections.Count)
            {
                EditorGUILayout.HelpBox($"Min Rooms cannot exceed the number of Sections ({sections.Count})", MessageType.Warning);
            }
            else
            {
                minRoomNum = newMinRoomNum;
            }

            // Max Rooms (minRoomNum以上、Section数以下)
            int newMaxRoomNum = EditorGUILayout.IntField("Max Rooms", maxRoomNum);
            if (newMaxRoomNum < minRoomNum)
            {
                EditorGUILayout.HelpBox($"Max Rooms must be at least {minRoomNum}", MessageType.Warning);
            }
            else if (newMaxRoomNum > sections.Count)
            {
                EditorGUILayout.HelpBox($"Max Rooms cannot exceed the number of Sections ({sections.Count})", MessageType.Warning);
            }
            else
            {
                maxRoomNum = newMaxRoomNum;
            }

            // Min Random Branches (0以上)
            minRandomBranchNum = EditorGUILayout.IntField("Min Branches", minRandomBranchNum);
            if (minRandomBranchNum < 0)
            {
                EditorGUILayout.HelpBox("Min Branches must be 0 or greater", MessageType.Warning);
            }

            // Max Random Branches (minRandomBranchNum以上)
            int newMaxRandomBranchNum = EditorGUILayout.IntField("Max Branches", maxRandomBranchNum);
            if (newMaxRandomBranchNum < minRandomBranchNum)
            {
                EditorGUILayout.HelpBox($"Max Branches must be at least {minRandomBranchNum}", MessageType.Warning);
            }
            else
            {
                maxRandomBranchNum = newMaxRandomBranchNum;
            }

            autoGenerateDefaultConnections = EditorGUILayout.Toggle("Auto Connections", autoGenerateDefaultConnections);

            GUILayout.Space(10);

            // 現在のBlueprint情報表示
            if (currentBlueprint != null)
            {
                GUILayout.Label("Editing: " + currentBlueprint.name, EditorStyles.boldLabel);
                GUILayout.Space(5);
            }

            // 新しいBlueprintを読み込むボタン
            if (GUILayout.Button("Load Blueprint", GUILayout.Height(25)))
            {
                LoadNewBlueprint();
            }

            // FieldBluePrint生成・保存ボタン
            if (currentBlueprint == null)
            {
                if (GUILayout.Button("Generate FieldBluePrint", GUILayout.Height(30)))
                {
                    GenerateFieldBluePrint();
                }
            }
            else
            {
                if (GUILayout.Button("Save Changes", GUILayout.Height(30)))
                {
                    SaveBlueprint();
                }


                GUILayout.Space(5);


                if (GUILayout.Button("Save As New Blueprint", GUILayout.Height(30)))
                {
                    GenerateFieldBluePrint();
                }
            }

            // ビューコントロール
            GUILayout.Label("View Controls", EditorStyles.boldLabel);
            GUILayout.Label("Zoom: Mouse Wheel");
            GUILayout.Label("Pan: Middle Mouse");

            GUILayout.Space(10);

            // ズームリセットボタン
            if (GUILayout.Button("Reset View"))
            {
                drawScale = 20f;
                viewOffset = Vector2Int.zero;
            }

            // ズームレベル表示
            GUILayout.Label($"Zoom: {drawScale:F1}x");

            GUILayout.Space(10);

            // 統計情報
            GUILayout.Label("Statistics", EditorStyles.boldLabel);
            GUILayout.Label($"Total Sections: {sections.Count}");

            int validSections = 0;
            foreach (var section in sections)
            {
                if (IsSectionInsideArea(section.rect))
                    validSections++;
            }
            GUILayout.Label($"Valid Sections: {validSections}");
            GUILayout.Label($"Total Connections: {connections.Count}");

            GUILayout.EndArea();
        }


    }
}