using RandomDungeonWithBluePrint;
using UnityEngine;
using UnityEditor;
using System.Collections.Generic;

namespace Editor
{
    public class FieldBluePrintEditor : EditorWindow
    {
        private Vector2Int boardSize = new Vector2Int(72, 48);
        private int minRoomNum = 5;
        private int maxRoomNum = 10;
        private int minRandomBranchNum = 1;
        private int maxRandomBranchNum = 3;
        private Vector2Int gridSize = new Vector2Int(4, 3);
        private Vector2Int minRoomSize = new Vector2Int(6, 6);

        [MenuItem("Assets/Create FieldBluePrint", false, 10)]
        public static void ShowWindow()
        {
            GetWindow<FieldBluePrintEditor>("Create FieldBluePrint");
        }

        void OnGUI()
        {
            GUILayout.Label("Configure your FieldBluePrint", EditorStyles.boldLabel);

            boardSize = EditorGUILayout.Vector2IntField("Board Size", boardSize);
            minRoomNum = EditorGUILayout.IntField("Minimum Room Number", minRoomNum);
            maxRoomNum = EditorGUILayout.IntField("Maximum Room Number", maxRoomNum);
            minRandomBranchNum = EditorGUILayout.IntField("Minimum Random Branch Number", minRandomBranchNum);
            maxRandomBranchNum = EditorGUILayout.IntField("Maximum Random Branch Number", maxRandomBranchNum);
            gridSize = EditorGUILayout.Vector2IntField("Grid Size", gridSize);
            minRoomSize = EditorGUILayout.Vector2IntField("Minimum Room Size", minRoomSize);

            if (GUILayout.Button("Generate FieldBluePrint"))
            {
                GenerateFieldBluePrint();
            }
        }

        void GenerateFieldBluePrint()
        {
            // 名前を自動生成
            string blueprintName = $"{boardSize.x}x{boardSize.y}_Grid{gridSize.x}x{gridSize.y}";

            List<FieldBluePrint.Section> sections = new List<FieldBluePrint.Section>();
            for (int i = 0; i < gridSize.x * gridSize.y; i++)
            {
                FieldBluePrint.Section section = new FieldBluePrint.Section(
                    i,
                    false,
                    1,
                    new RectInt(i % gridSize.x * (boardSize.x / gridSize.x), i / gridSize.x * (boardSize.y / gridSize.y), boardSize.x / gridSize.x, boardSize.y / gridSize.y),
                    minRoomSize
                );
                sections.Add(section);
            }

            List<FieldBluePrint.Connection> connections = new List<FieldBluePrint.Connection>();

            FieldBluePrint blueprint = new FieldBluePrint(
                boardSize,
                minRoomNum,
                maxRoomNum,
                minRandomBranchNum,
                maxRandomBranchNum,
                true, //autoGenerateDefaultConnections
                sections,
                connections
            );

            string path = AssetDatabase.GetAssetPath(Selection.activeObject);
            if (string.IsNullOrEmpty(path))
            {
                path = "Assets";
            }
            else if (!System.IO.Directory.Exists(path))
            {
                path = System.IO.Path.GetDirectoryName(path);
            }

            string assetPathAndName = AssetDatabase.GenerateUniqueAssetPath(path + $"/{blueprintName}.asset");
            AssetDatabase.CreateAsset(blueprint, assetPathAndName);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            EditorUtility.FocusProjectWindow();
            Selection.activeObject = blueprint;

            Debug.Log("FieldBluePrint created at: " + assetPathAndName);
        }
    }
}