namespace Utilities
{
    public enum ParticleType
    {
        Blind,
        Blood,
        BloodRage,
        Burn,
        Cold,
        Confusion,
        Electric,
        Energy,
        FastHeal,
        FastSpeed,
        Fear,
        HealGreen,
        Paralysis,
        PoisoningSmoke,
        PoisoningBubble,
        PowerUp,
        Relieve,
        ShineyStar,
        Sleep,
        SlowDown,
        Stuned,
        SuckBlood,
        Rage
    }
}